#!/bin/bash
set -o errexit
set -o xtrace

if [[ ! -d "/etc/kubez-nginx" ]]; then
    mkdir -p /etc/kubez-nginx
fi

if [[ ! -d "/etc/kubez-nginx/logs" ]]; then
    mkdir -p /etc/kubez-nginx/logs
fi

echo "Running kubez-nginx command"
/kubez-nginx -c /etc/kubez-nginx/kubez-nginx.conf -p /etc/kubez-nginx -g 'daemon off;'
